# Generated by Django 4.2.4 on 2023-10-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cake',
            new_name='cakes',
        ),
    ]
