# Generated by Django 4.2.4 on 2023-11-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0002_rename_cake_cakes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cakevarient',
            new_name='cakevarients',
        ),
    ]
