# Generated by Django 4.2.4 on 2023-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delight', '0004_remove_reviews_cakevarient_reviews_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakevarients',
            name='flavor',
        ),
        migrations.AddField(
            model_name='cakes',
            name='flavor',
            field=models.CharField(choices=[('chocolate', 'chocolate'), ('vanilla', 'vanilla'), ('pistachio', 'pistachio'), ('tropical rum', 'tropical rum'), ('pineapple', 'pineapple'), ('red velvet', 'red velvet')], default='chocolate', max_length=200),
        ),
    ]
